### ISSUE TITLE
How to use Brew package options?

### ISSUE THREAD

**Issue by pe3** [osxc/legacy-common#51]
Hello

How can I do a `brew install libav --with-theora --with-libvorbis --with-libvo-aacenc --with-libvpx` in all.yml?

I have tried many things among them:

```
 - role: brew_package
    package_name: libav
    brew_opts: 
      - with-theora
      - with-libvorbis
      - with-libvo-aacenc
      - with-libvpx
```

**Comment by ninjabong** [comment]
it's a little funky since we're just wrapping [ansible's original homebrew role](http://docs.ansible.com/homebrew_module.html), but what you want should be:

``` yaml
- role: brew_package
  package_name: libav
  brew_opts: with-theora,with-libvorbis,with-libvo-aacenc,with-libvpx
```
